//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET2.MemberSettingsSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadMemberSiteSettingsParams", Namespace="EFSchools.Englishtown.SharedServices.Client.MemberSettings.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoadMemberSiteSettingsParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Member_idField;
        
        private string SiteAreaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Member_id {
            get {
                return this.Member_idField;
            }
            set {
                if ((this.Member_idField.Equals(value) != true)) {
                    this.Member_idField = value;
                    this.RaisePropertyChanged("Member_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SiteArea {
            get {
                return this.SiteAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteAreaField, value) != true)) {
                    this.SiteAreaField = value;
                    this.RaisePropertyChanged("SiteArea");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadMemberSiteSettingsResult", Namespace="EFSchools.Englishtown.SharedServices.Client.MemberSettings.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoadMemberSiteSettingsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<string, string> SiteSettingsField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> SiteSettings {
            get {
                return this.SiteSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteSettingsField, value) != true)) {
                    this.SiteSettingsField = value;
                    this.RaisePropertyChanged("SiteSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveMemberSiteSettingParams", Namespace="EFSchools.Englishtown.SharedServices.Client.MemberSettings.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SaveMemberSiteSettingParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Member_idField;
        
        private string SiteAreaField;
        
        private string KeyCodeField;
        
        private string KeyValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Member_id {
            get {
                return this.Member_idField;
            }
            set {
                if ((this.Member_idField.Equals(value) != true)) {
                    this.Member_idField = value;
                    this.RaisePropertyChanged("Member_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SiteArea {
            get {
                return this.SiteAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteAreaField, value) != true)) {
                    this.SiteAreaField = value;
                    this.RaisePropertyChanged("SiteArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string KeyCode {
            get {
                return this.KeyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyCodeField, value) != true)) {
                    this.KeyCodeField = value;
                    this.RaisePropertyChanged("KeyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string KeyValue {
            get {
                return this.KeyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyValueField, value) != true)) {
                    this.KeyValueField = value;
                    this.RaisePropertyChanged("KeyValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveMemberSiteSettingResult", Namespace="EFSchools.Englishtown.SharedServices.Client.MemberSettings.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SaveMemberSiteSettingResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="EFSchools.Englishtown.SharedServices.Client.MemberSettings", ConfigurationName="MemberSettingsSvc.IMemberSettingsService")]
    public interface IMemberSettingsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/LoadMemberSiteSettings", ReplyAction="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/LoadMemberSiteSettingsResponse")]
        ET2.MemberSettingsSvc.LoadMemberSiteSettingsResult LoadMemberSiteSettings(ET2.MemberSettingsSvc.LoadMemberSiteSettingsParams input);
        
        [System.ServiceModel.OperationContractAttribute(Action="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/LoadMemberSiteSettings", ReplyAction="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/LoadMemberSiteSettingsResponse")]
        System.Threading.Tasks.Task<ET2.MemberSettingsSvc.LoadMemberSiteSettingsResult> LoadMemberSiteSettingsAsync(ET2.MemberSettingsSvc.LoadMemberSiteSettingsParams input);
        
        [System.ServiceModel.OperationContractAttribute(Action="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/SaveMemberSiteSetting", ReplyAction="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/SaveMemberSiteSettingResponse")]
        ET2.MemberSettingsSvc.SaveMemberSiteSettingResult SaveMemberSiteSetting(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams input);
        
        [System.ServiceModel.OperationContractAttribute(Action="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/SaveMemberSiteSetting", ReplyAction="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/SaveMemberSiteSettingResponse")]
        System.Threading.Tasks.Task<ET2.MemberSettingsSvc.SaveMemberSiteSettingResult> SaveMemberSiteSettingAsync(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams input);
        
        [System.ServiceModel.OperationContractAttribute(Action="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/BatchSaveMemberSiteSetting", ReplyAction="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/BatchSaveMemberSiteSettingResponse")]
        ET2.MemberSettingsSvc.SaveMemberSiteSettingResult BatchSaveMemberSiteSetting(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams[] memberSiteSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/BatchSaveMemberSiteSetting", ReplyAction="EFSchools.Englishtown.SharedServices.Client.MemberSettings/IMemberSettingsService" +
            "/BatchSaveMemberSiteSettingResponse")]
        System.Threading.Tasks.Task<ET2.MemberSettingsSvc.SaveMemberSiteSettingResult> BatchSaveMemberSiteSettingAsync(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams[] memberSiteSettings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberSettingsServiceChannel : ET2.MemberSettingsSvc.IMemberSettingsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberSettingsServiceClient : System.ServiceModel.ClientBase<ET2.MemberSettingsSvc.IMemberSettingsService>, ET2.MemberSettingsSvc.IMemberSettingsService {
        
        public MemberSettingsServiceClient() {
        }
        
        public MemberSettingsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberSettingsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberSettingsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberSettingsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ET2.MemberSettingsSvc.LoadMemberSiteSettingsResult LoadMemberSiteSettings(ET2.MemberSettingsSvc.LoadMemberSiteSettingsParams input) {
            return base.Channel.LoadMemberSiteSettings(input);
        }
        
        public System.Threading.Tasks.Task<ET2.MemberSettingsSvc.LoadMemberSiteSettingsResult> LoadMemberSiteSettingsAsync(ET2.MemberSettingsSvc.LoadMemberSiteSettingsParams input) {
            return base.Channel.LoadMemberSiteSettingsAsync(input);
        }
        
        public ET2.MemberSettingsSvc.SaveMemberSiteSettingResult SaveMemberSiteSetting(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams input) {
            return base.Channel.SaveMemberSiteSetting(input);
        }
        
        public System.Threading.Tasks.Task<ET2.MemberSettingsSvc.SaveMemberSiteSettingResult> SaveMemberSiteSettingAsync(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams input) {
            return base.Channel.SaveMemberSiteSettingAsync(input);
        }
        
        public ET2.MemberSettingsSvc.SaveMemberSiteSettingResult BatchSaveMemberSiteSetting(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams[] memberSiteSettings) {
            return base.Channel.BatchSaveMemberSiteSetting(memberSiteSettings);
        }
        
        public System.Threading.Tasks.Task<ET2.MemberSettingsSvc.SaveMemberSiteSettingResult> BatchSaveMemberSiteSettingAsync(ET2.MemberSettingsSvc.SaveMemberSiteSettingParams[] memberSiteSettings) {
            return base.Channel.BatchSaveMemberSiteSettingAsync(memberSiteSettings);
        }
    }
}
